In [169]:
import pandas as pd
import numpy as np
df=pd.read_csv('최종감성분석.csv')
df2=pd.read_csv('최종 데이터(for추천).csv')

In [170]:
df.head()

,관광지,전체내용,리뷰내용_1,리뷰내용_0,긍정확률_0,부정확률_0,긍정확률_1,부정확률_1
0,경복궁,"['대한민국의 역사 ', ' 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 ...",대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복...,대한민국의 역사,0.987351,0.012649,0.998123,0.001877
1,경복궁,"['국민이 공감하는 장소 ', ' 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에...",경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특...,국민이 공감하는 장소,0.953610,0.046390,0.996655,0.003345
2,경복궁,"['산책하기 좋은 경복궁 ', ' 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음...",날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요?...,산책하기 좋은 경복궁,0.831948,0.168052,0.998227,0.001773
3,경복궁,"['Good ', ' Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관...",Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도...,Good,0.996760,0.003240,0.998211,0.001789
4,경복궁,"['가족단위로 방문하기 좋은곳 ', ' 요새 더더욱 코로나로 인해 사람 방문이 적음...",요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금...,가족단위로 방문하기 좋은곳,0.989706,0.010294,0.145126,0.854874

In [171]:
len(df['리뷰내용_1'][0]), len(df['리뷰내용_0'][0])

(87, 9)

In [172]:
df.dropna(axis=0,inplace=True)

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5355 entries, 0 to 5355
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관광지     5355 non-null   object
 1   전체내용    5355 non-null   object
 2   리뷰내용_1  5355 non-null   object
 3   리뷰내용_0  5355 non-null   object
 4   긍정확률_0  5355 non-null   float64
 5   부정확률_0  5355 non-null   float64
 6   긍정확률_1  5355 non-null   float64
 7   부정확률_1  5355 non-null   float64
dtypes: float64(4), object(4)
memory usage: 376.5+ KB

# 리뷰 없음이 포함된 데이터

In [174]:
df_a=df[df['리뷰내용_1'].str.contains('리뷰없음')]

In [175]:
df_a

,관광지,전체내용,리뷰내용_1,리뷰내용_0,긍정확률_0,부정확률_0,긍정확률_1,부정확률_1
4698,암사동 선사주거지,['신석기 시대를 체험할 수 있다'],리뷰없음,신석기 시대를 체험할 수 있다,0.720194,0.279806,0.047169,0.952831
4699,암사동 선사주거지,['교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하...,리뷰없음,교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하기 ...,0.997674,0.002326,0.047169,0.952831
4700,암사동 선사주거지,['유적지'],리뷰없음,유적지,0.583637,0.416363,0.047169,0.952831
4701,암사동 선사주거지,['아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가...,리뷰없음,아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가족 ...,0.996315,0.003685,0.047169,0.952831
4702,암사동 선사주거지,['아이들 봉사활동할 꺼리도 있ㄱ'],리뷰없음,아이들 봉사활동할 꺼리도 있ㄱ,0.092964,0.907036,0.047169,0.952831
...,...,...,...,...,...,...,...,...
5351,순천 드라마세트장,['서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새...,리뷰없음,서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특...,0.311129,0.688871,0.005893,0.994107
5352,순천 드라마세트장,['사진찍기 좋은 날에~~^^'],리뷰없음,사진찍기 좋은 날에,0.848867,0.151133,0.005893,0.994107
5353,순천 드라마세트장,['기분 좋은 그 어떤 날~~~ 그 곳에선 그 어떠한 모습도 예쁘...,리뷰없음,기분 좋은 그 어떤 날 그 곳에선 그 어떠한 모습도 예쁘고 사랑...,0.962142,0.037858,0.005893,0.994107
5354,순천 드라마세트장,['재밌네요ㅎ'],리뷰없음,재밌네요ㅎ,0.934410,0.065590,0.005893,0.994107
5355,순천 드라마세트장,['드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고...,리뷰없음,드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예...,0.984369,0.015631,0.005893,0.994107

In [176]:
df_a['최종긍정확률']=df_a['긍정확률_0']
df_a['최종부정확률']=df_a['부정확률_0']

<ipython-input-176-0d8474c36002>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_a['최종긍정확률']=df_a['긍정확률_0']
<ipython-input-176-0d8474c36002>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_a['최종부정확률']=df_a['부정확률_0']

In [177]:
df_a.head()

,관광지,전체내용,리뷰내용_1,리뷰내용_0,긍정확률_0,부정확률_0,긍정확률_1,부정확률_1,최종긍정확률,최종부정확률
4698,암사동 선사주거지,['신석기 시대를 체험할 수 있다'],리뷰없음,신석기 시대를 체험할 수 있다,0.720194,0.279806,0.047169,0.952831,0.720194,0.279806
4699,암사동 선사주거지,['교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하...,리뷰없음,교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하기 ...,0.997674,0.002326,0.047169,0.952831,0.997674,0.002326
4700,암사동 선사주거지,['유적지'],리뷰없음,유적지,0.583637,0.416363,0.047169,0.952831,0.583637,0.416363
4701,암사동 선사주거지,['아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가...,리뷰없음,아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가족 ...,0.996315,0.003685,0.047169,0.952831,0.996315,0.003685
4702,암사동 선사주거지,['아이들 봉사활동할 꺼리도 있ㄱ'],리뷰없음,아이들 봉사활동할 꺼리도 있ㄱ,0.092964,0.907036,0.047169,0.952831,0.092964,0.907036

In [178]:
df_a['리뷰']=df_a['리뷰내용_0']

<ipython-input-178-f62ecd3d1e54>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_a['리뷰']=df_a['리뷰내용_0']

In [179]:
df_a.drop(['긍정확률_0','부정확률_0','긍정확률_1','부정확률_1'],axis=1,inplace=True)

C:\anaconda\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [180]:
df_a

,관광지,전체내용,리뷰내용_1,리뷰내용_0,최종긍정확률,최종부정확률,리뷰
4698,암사동 선사주거지,['신석기 시대를 체험할 수 있다'],리뷰없음,신석기 시대를 체험할 수 있다,0.720194,0.279806,신석기 시대를 체험할 수 있다
4699,암사동 선사주거지,['교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하...,리뷰없음,교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하기 ...,0.997674,0.002326,교과서에서만 보던 선사 유적지이다. 서울 외곽에 위치해 있어서 대중됴통을 이용하기 ...
4700,암사동 선사주거지,['유적지'],리뷰없음,유적지,0.583637,0.416363,유적지
4701,암사동 선사주거지,['아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가...,리뷰없음,아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가족 ...,0.996315,0.003685,아이들과 함께 하거나 어르신들 모시고 나들이 가기 좋은 곳이네요. 온 가족이 가족 ...
4702,암사동 선사주거지,['아이들 봉사활동할 꺼리도 있ㄱ'],리뷰없음,아이들 봉사활동할 꺼리도 있ㄱ,0.092964,0.907036,아이들 봉사활동할 꺼리도 있ㄱ
...,...,...,...,...,...,...,...
5351,순천 드라마세트장,['서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새...,리뷰없음,서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특...,0.311129,0.688871,서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특...
5352,순천 드라마세트장,['사진찍기 좋은 날에~~^^'],리뷰없음,사진찍기 좋은 날에,0.848867,0.151133,사진찍기 좋은 날에
5353,순천 드라마세트장,['기분 좋은 그 어떤 날~~~ 그 곳에선 그 어떠한 모습도 예쁘...,리뷰없음,기분 좋은 그 어떤 날 그 곳에선 그 어떠한 모습도 예쁘고 사랑...,0.962142,0.037858,기분 좋은 그 어떤 날 그 곳에선 그 어떠한 모습도 예쁘고 사랑...
5354,순천 드라마세트장,['재밌네요ㅎ'],리뷰없음,재밌네요ㅎ,0.934410,0.065590,재밌네요ㅎ
5355,순천 드라마세트장,['드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고...,리뷰없음,드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예...,0.984369,0.015631,드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예...

# 정상적인 데이터

In [181]:
df_b=df[~df['리뷰내용_1'].str.contains('리뷰없음')]
df_b.head()

,관광지,전체내용,리뷰내용_1,리뷰내용_0,긍정확률_0,부정확률_0,긍정확률_1,부정확률_1
0,경복궁,"['대한민국의 역사 ', ' 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 ...",대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복...,대한민국의 역사,0.987351,0.012649,0.998123,0.001877
1,경복궁,"['국민이 공감하는 장소 ', ' 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에...",경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특...,국민이 공감하는 장소,0.953610,0.046390,0.996655,0.003345
2,경복궁,"['산책하기 좋은 경복궁 ', ' 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음...",날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요?...,산책하기 좋은 경복궁,0.831948,0.168052,0.998227,0.001773
3,경복궁,"['Good ', ' Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관...",Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도...,Good,0.996760,0.003240,0.998211,0.001789
4,경복궁,"['가족단위로 방문하기 좋은곳 ', ' 요새 더더욱 코로나로 인해 사람 방문이 적음...",요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금...,가족단위로 방문하기 좋은곳,0.989706,0.010294,0.145126,0.854874

In [182]:
df_b['최종긍정확률']=(df_b['긍정확률_0']+df_b['긍정확률_1'])/2
df_b['최종부정확률']=(df_b['부정확률_0']+df_b['부정확률_1'])/2

<ipython-input-182-c8329258e7b3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_b['최종긍정확률']=(df_b['긍정확률_0']+df_b['긍정확률_1'])/2
<ipython-input-182-c8329258e7b3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_b['최종부정확률']=(df_b['부정확률_0']+df_b['부정확률_1'])/2

In [183]:
df_b['리뷰']=df_b['리뷰내용_0'] + df_b['리뷰내용_1']

<ipython-input-183-effac1741632>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_b['리뷰']=df_b['리뷰내용_0'] + df_b['리뷰내용_1']

In [184]:
df_b.head()

,관광지,전체내용,리뷰내용_1,리뷰내용_0,긍정확률_0,부정확률_0,긍정확률_1,부정확률_1,최종긍정확률,최종부정확률,리뷰
0,경복궁,"['대한민국의 역사 ', ' 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 ...",대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복...,대한민국의 역사,0.987351,0.012649,0.998123,0.001877,0.992737,0.007263,대한민국의 역사 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야...
1,경복궁,"['국민이 공감하는 장소 ', ' 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에...",경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특...,국민이 공감하는 장소,0.953610,0.046390,0.996655,0.003345,0.975133,0.024867,국민이 공감하는 장소 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족...
2,경복궁,"['산책하기 좋은 경복궁 ', ' 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음...",날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요?...,산책하기 좋은 경복궁,0.831948,0.168052,0.998227,0.001773,0.915088,0.084912,산책하기 좋은 경복궁 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지...
3,경복궁,"['Good ', ' Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관...",Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도...,Good,0.996760,0.003240,0.998211,0.001789,0.997485,0.002515,Good Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁,"['가족단위로 방문하기 좋은곳 ', ' 요새 더더욱 코로나로 인해 사람 방문이 적음...",요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금...,가족단위로 방문하기 좋은곳,0.989706,0.010294,0.145126,0.854874,0.567416,0.432584,가족단위로 방문하기 좋은곳 요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 ...

In [185]:
df_b.drop(['긍정확률_0','부정확률_0','긍정확률_1','부정확률_1'],axis=1,inplace=True)

C:\anaconda\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [186]:
df_b

,관광지,전체내용,리뷰내용_1,리뷰내용_0,최종긍정확률,최종부정확률,리뷰
0,경복궁,"['대한민국의 역사 ', ' 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 ...",대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복...,대한민국의 역사,0.992737,0.007263,대한민국의 역사 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야...
1,경복궁,"['국민이 공감하는 장소 ', ' 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에...",경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특...,국민이 공감하는 장소,0.975133,0.024867,국민이 공감하는 장소 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족...
2,경복궁,"['산책하기 좋은 경복궁 ', ' 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음...",날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요?...,산책하기 좋은 경복궁,0.915088,0.084912,산책하기 좋은 경복궁 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지...
3,경복궁,"['Good ', ' Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관...",Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도...,Good,0.997485,0.002515,Good Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁,"['가족단위로 방문하기 좋은곳 ', ' 요새 더더욱 코로나로 인해 사람 방문이 적음...",요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금...,가족단위로 방문하기 좋은곳,0.567416,0.432584,가족단위로 방문하기 좋은곳 요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 ...
...,...,...,...,...,...,...,...
4695,제주 감귤박물관,['감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양합니다. 아이들과...,제주도의 역사에대해 나와있습니다.,감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양합니다. 아이들과 방...,0.732150,0.267850,감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양합니다. 아이들과 방...
4696,제주 감귤박물관,['생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 있으며 체험도 할...,감귤박물관,생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 있으며 체험도 할 수...,0.707135,0.292865,생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 있으며 체험도 할 수...
4697,제주 감귤박물관,['감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던 것이 3000원...,신나는 감귤 축제,감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던 것이 3000원으로...,0.787530,0.212470,감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던 것이 3000원으로...
4751,국립현대미술관(과천관),"['[세상에 눈뜨다', ' 아시아 미술과 사회 1960s-1990s] 전시에서 아시...","아시아 미술과 사회 1960s-1990s] 전시에서 아시아의 현대, 사회참여적 미...",[세상에 눈뜨다,0.996504,0.003496,"[세상에 눈뜨다 아시아 미술과 사회 1960s-1990s] 전시에서 아시아의 현대,..."
5101,창녕 석빙고,['조선시대에 지어진 얼음 보관 창고입니다. 신라와는 관련이 없는 유적이긴 하지만 ...,무료,조선시대에 지어진 얼음 보관 창고입니다. 신라와는 관련이 없는 유적이긴 하지만 여름...,0.501107,0.498893,조선시대에 지어진 얼음 보관 창고입니다. 신라와는 관련이 없는 유적이긴 하지만 여름...

In [187]:
df=pd.concat([df_b,df_a])
df

,관광지,전체내용,리뷰내용_1,리뷰내용_0,최종긍정확률,최종부정확률,리뷰
0,경복궁,"['대한민국의 역사 ', ' 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 ...",대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복...,대한민국의 역사,0.992737,0.007263,대한민국의 역사 대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야...
1,경복궁,"['국민이 공감하는 장소 ', ' 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에...",경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특...,국민이 공감하는 장소,0.975133,0.024867,국민이 공감하는 장소 경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족...
2,경복궁,"['산책하기 좋은 경복궁 ', ' 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음...",날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요?...,산책하기 좋은 경복궁,0.915088,0.084912,산책하기 좋은 경복궁 날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지...
3,경복궁,"['Good ', ' Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관...",Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도...,Good,0.997485,0.002515,Good Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁,"['가족단위로 방문하기 좋은곳 ', ' 요새 더더욱 코로나로 인해 사람 방문이 적음...",요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금...,가족단위로 방문하기 좋은곳,0.567416,0.432584,가족단위로 방문하기 좋은곳 요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 ...
...,...,...,...,...,...,...,...
5351,순천 드라마세트장,['서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새...,리뷰없음,서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특...,0.311129,0.688871,서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특...
5352,순천 드라마세트장,['사진찍기 좋은 날에~~^^'],리뷰없음,사진찍기 좋은 날에,0.848867,0.151133,사진찍기 좋은 날에
5353,순천 드라마세트장,['기분 좋은 그 어떤 날~~~ 그 곳에선 그 어떠한 모습도 예쁘...,리뷰없음,기분 좋은 그 어떤 날 그 곳에선 그 어떠한 모습도 예쁘고 사랑...,0.962142,0.037858,기분 좋은 그 어떤 날 그 곳에선 그 어떠한 모습도 예쁘고 사랑...
5354,순천 드라마세트장,['재밌네요ㅎ'],리뷰없음,재밌네요ㅎ,0.934410,0.065590,재밌네요ㅎ
5355,순천 드라마세트장,['드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고...,리뷰없음,드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예...,0.984369,0.015631,드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예...

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5355 entries, 0 to 5355
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관광지     5355 non-null   object
 1   전체내용    5355 non-null   object
 2   리뷰내용_1  5355 non-null   object
 3   리뷰내용_0  5355 non-null   object
 4   최종긍정확률  5355 non-null   float64
 5   최종부정확률  5355 non-null   float64
 6   리뷰      5355 non-null   object
dtypes: float64(2), object(5)
memory usage: 334.7+ KB

In [189]:
df=df[['관광지','리뷰','최종긍정확률','최종부정확률']]

In [190]:
df.head()

   관광지                                                 리뷰    최종긍정확률    최종부정확률
0  경복궁  대한민국의 역사  대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야...  0.992737  0.007263
1  경복궁  국민이 공감하는 장소  경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족...  0.975133  0.024867
2  경복궁  산책하기 좋은 경복궁  날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지...  0.915088  0.084912
3  경복궁  Good  Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...  0.997485  0.002515
4  경복궁  가족단위로 방문하기 좋은곳  요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 ...  0.567416  0.432584

In [191]:
df_group=df.groupby(['관광지'],as_index=False).mean()

In [192]:
df_group

                  관광지    최종긍정확률    최종부정확률
0               63스퀘어  0.792686  0.207314
1             BIFF 광장  0.544369  0.455631
2    SEA LIFE 부산아쿠아리움  0.714060  0.285940
3            가야산 국립공원  0.897052  0.102948
4                 간월재  0.802439  0.197561
..                ...       ...       ...
609                황지  0.811460  0.188540
610              회암사지  0.997762  0.002238
611        휴애리 자연생활공원  0.773505  0.226495
612               흑산도  0.625063  0.374937
613        흥정계곡과 허브나라  0.756666  0.243334

[614 rows x 3 columns]

In [193]:
df_group.rename(columns={'관광지':'여행지'},inplace=True)

In [194]:
df_group['최종긍정확률'].median()

0.8153577034375

In [195]:
df_group['최종부정확률'].median()

0.18464229333749999

In [196]:
df2=pd.read_csv('최종 데이터(for추천).csv')

In [197]:
df2=df2.sort_values('여행지')
df2

,여행지,주소,행정구역,시군구,분류,트립어드바이저평점,카테고리
49,63스퀘어,"영등포구 63로 50, 서울",서울시,영등포구,건축물,4,랜드마크
529,BIFF 광장,"중구 남포동, 부산",부산광역시,중구,즐길거리 & 랜드마크,4,랜드마크
538,SEA LIFE 부산아쿠아리움,"해운대구 해운대해변로 266, 부산",부산광역시,해운대구,수족관,4,랜드마크
522,가야산 국립공원,경남 합천군 가야면,경상남도,합천군,국립공원,4.5,공원
269,간월재,"울주군 상북면, 울산",울산광역시,울주군,산림,4.5,산
...,...,...,...,...,...,...,...
170,황지,"황지동 25-4, 태백",강원도,태백시,물길,4,자연 경관
108,회암사지,"회암사길 281, 양주, 경기도",경기도,양주시,종교적인 장소,5,종교적인 장소
608,휴애리 자연생활공원,"남원읍 신례동로 256, 서귀포",제주특별자치시,서귀포시,공원,4,공원
396,흑산도,"Dadohae National Marine Park, 신안",전라남도,신안군,섬,5,섬
200,흥정계곡과 허브나라,"봉평면 흥정리, 평창",강원도,평창군,계곡,4.5,자연 경관

In [198]:
df2.head()

,여행지,주소,행정구역,시군구,분류,트립어드바이저평점,카테고리
49,63스퀘어,"영등포구 63로 50, 서울",서울시,영등포구,건축물,4,랜드마크
529,BIFF 광장,"중구 남포동, 부산",부산광역시,중구,즐길거리 & 랜드마크,4,랜드마크
538,SEA LIFE 부산아쿠아리움,"해운대구 해운대해변로 266, 부산",부산광역시,해운대구,수족관,4,랜드마크
522,가야산 국립공원,경남 합천군 가야면,경상남도,합천군,국립공원,4.5,공원
269,간월재,"울주군 상북면, 울산",울산광역시,울주군,산림,4.5,산

In [199]:
dfs=pd.merge(df2,df_group,on='여행지')
dfs

,여행지,주소,행정구역,시군구,분류,트립어드바이저평점,카테고리,최종긍정확률,최종부정확률
0,63스퀘어,"영등포구 63로 50, 서울",서울시,영등포구,건축물,4,랜드마크,0.792686,0.207314
1,BIFF 광장,"중구 남포동, 부산",부산광역시,중구,즐길거리 & 랜드마크,4,랜드마크,0.544369,0.455631
2,SEA LIFE 부산아쿠아리움,"해운대구 해운대해변로 266, 부산",부산광역시,해운대구,수족관,4,랜드마크,0.714060,0.285940
3,가야산 국립공원,경남 합천군 가야면,경상남도,합천군,국립공원,4.5,공원,0.897052,0.102948
4,간월재,"울주군 상북면, 울산",울산광역시,울주군,산림,4.5,산,0.802439,0.197561
...,...,...,...,...,...,...,...,...,...
613,황지,"황지동 25-4, 태백",강원도,태백시,물길,4,자연 경관,0.811460,0.188540
614,회암사지,"회암사길 281, 양주, 경기도",경기도,양주시,종교적인 장소,5,종교적인 장소,0.997762,0.002238
615,휴애리 자연생활공원,"남원읍 신례동로 256, 서귀포",제주특별자치시,서귀포시,공원,4,공원,0.773505,0.226495
616,흑산도,"Dadohae National Marine Park, 신안",전라남도,신안군,섬,5,섬,0.625063,0.374937
617,흥정계곡과 허브나라,"봉평면 흥정리, 평창",강원도,평창군,계곡,4.5,자연 경관,0.756666,0.243334

In [200]:
df2

,여행지,주소,행정구역,시군구,분류,트립어드바이저평점,카테고리
49,63스퀘어,"영등포구 63로 50, 서울",서울시,영등포구,건축물,4,랜드마크
529,BIFF 광장,"중구 남포동, 부산",부산광역시,중구,즐길거리 & 랜드마크,4,랜드마크
538,SEA LIFE 부산아쿠아리움,"해운대구 해운대해변로 266, 부산",부산광역시,해운대구,수족관,4,랜드마크
522,가야산 국립공원,경남 합천군 가야면,경상남도,합천군,국립공원,4.5,공원
269,간월재,"울주군 상북면, 울산",울산광역시,울주군,산림,4.5,산
...,...,...,...,...,...,...,...
170,황지,"황지동 25-4, 태백",강원도,태백시,물길,4,자연 경관
108,회암사지,"회암사길 281, 양주, 경기도",경기도,양주시,종교적인 장소,5,종교적인 장소
608,휴애리 자연생활공원,"남원읍 신례동로 256, 서귀포",제주특별자치시,서귀포시,공원,4,공원
396,흑산도,"Dadohae National Marine Park, 신안",전라남도,신안군,섬,5,섬
200,흥정계곡과 허브나라,"봉평면 흥정리, 평창",강원도,평창군,계곡,4.5,자연 경관

In [201]:
df2

,여행지,주소,행정구역,시군구,분류,트립어드바이저평점,카테고리
49,63스퀘어,"영등포구 63로 50, 서울",서울시,영등포구,건축물,4,랜드마크
529,BIFF 광장,"중구 남포동, 부산",부산광역시,중구,즐길거리 & 랜드마크,4,랜드마크
538,SEA LIFE 부산아쿠아리움,"해운대구 해운대해변로 266, 부산",부산광역시,해운대구,수족관,4,랜드마크
522,가야산 국립공원,경남 합천군 가야면,경상남도,합천군,국립공원,4.5,공원
269,간월재,"울주군 상북면, 울산",울산광역시,울주군,산림,4.5,산
...,...,...,...,...,...,...,...
170,황지,"황지동 25-4, 태백",강원도,태백시,물길,4,자연 경관
108,회암사지,"회암사길 281, 양주, 경기도",경기도,양주시,종교적인 장소,5,종교적인 장소
608,휴애리 자연생활공원,"남원읍 신례동로 256, 서귀포",제주특별자치시,서귀포시,공원,4,공원
396,흑산도,"Dadohae National Marine Park, 신안",전라남도,신안군,섬,5,섬
200,흥정계곡과 허브나라,"봉평면 흥정리, 평창",강원도,평창군,계곡,4.5,자연 경관

In [203]:
dfs.to_csv('감성분석있는것들만데이터.csv',index=False,encoding='utf-8-sig')

In [121]:
len(dfs)

618

In [122]:
len(df2)

658

In [123]:
dfs['여행지'].set()

AttributeError: 'Series' object has no attribute 'set'

In [124]:
df2.compare(dfs)

ValueError: Can only compare identically-labeled DataFrame objects

In [125]:
dfs['여행지'].unique()

array(['63스퀘어', 'BIFF 광장', 'SEA LIFE 부산아쿠아리움', '가야산 국립공원', '간월재', '간절곶',
       '감은사지', '갑곶돈대', '갑사', '강릉선교장', '강진 청자박물관', '강천산', '강촌', '강화 풍물시장',
       '강화역사박물관', '개실마을', '개심사', '개암사', '거북선모형관', '거제 포로수용소 유적공원', '건봉사',
       '검룡소', '경교장', '경기도립 물향기수목원', '경기전', '경복궁', '경상남도수목원', '경상북도 수목원',
       '경천대', '계룡산 국립공원', '계림', '고려궁지', '고모산성', '고분군', '고석정', '고성 공룡박물관',
       '고성 탈박물관', '고운사', '고운식물원', '고창 고인돌 박물관', '고창읍성', '고추장마을', '곤충박물관',
       '곰소염전', '공산성', '관룡사', '관악산', '관촉사', '광성보와 용두돈대', '광안대교',
       '광양 장도박물관', '광한루원', '괘릉', '괴시리 전통마을', '구곡폭포', '구문소', '구암리 지석묘 무리',
       '구인사', '구지봉', '국립 5ㆍ18 민주묘지', '국립경주박물관', '국립공주박물관', '국립과천과학관',
       '국립광주박물관', '국립김해박물관', '국립민속박물관', '국립부여박물관', '국립서울현충원', '국립수목원',
       '국립중앙과학관', '국립중앙박물관', '국립진주박물관', '국립춘천박물관', '국립해양생물자원관',
       '국립해양유물전시관', '국립현대미술관(과천관)', '국립현대미술관(서울관)', '국망봉 자연휴양림',
       '군위 삼존석굴', '궁남지', '그림이 있는 정원', '금강 공원', '금강 철새조망대', '금능해수욕장',
       '금둔사', '금릉 경포대', '금산 보리암', '금산 인삼축제', '금산사', '금성산 고분군', '금오산',
       '기장시장', '길상사', '김녕 미로공원', '김성종 추리문학관', '김영갑 갤러리', '김영갑 갤러리 두모악',
       '김유정 문학촌', '꽃지해수욕장', '나주 배마을과 배박물관', '낙동강하구에코센터', '낙산공원', '낙산사',
       '낙산해수욕장', '낙안읍성', '남대문시장', '남사 예담촌', '남사당 전수관', '남산골 한옥마을',
       '남산과 N서울타워', '남애항과 남애해수욕장', '남이섬', '남한산성도립공원', '내소사', '내연산 군립공원',
       '내장사', '내장산 국립공원', '노동당사', '농업박물관', '누리마루 APEC 하우스', '능산리 고분군',
       '다랑쉬오름', '다랭이마을', '다산초당', '다솔사', '달아공원', '담양온천', '대가야박물관',
       '대관령 삼양목장', '대금굴', '대둔산', '대릉원', '대부도', '대성동 고분박물관', '대왕암 공원',
       '대원사와 티베트박물관', '대천해수욕장', '대포 주상절리', '대포항', '대한민국 국회의사당과 헌정기념관',
       '대흥사', '덕구온천 스파월드', '덕수궁', '덕유산 국립공원', '덕진공원', '덕포진', '덕포진 교육박물관',
       '도담삼봉', '도봉산', '도산서원', '도피안사', '독도박물관', '독립기념관', '독립문',
       '돌산대교와 돌산공원', '동구릉', '동대문디자인플라자', '동대문시장', '동막해변', '동학사',
       '동학혁명기념관', '돝섬해상유원지', '두륜산 케이블카', '두물머리', '두타연계곡', '땅끝마을', '로보파크',
       '롯데월드', '마곡사', '마니산과 참성단', '마량리 동백숲', '마량항', '마이산 도립공원',
       '만성리 검은모래해수욕장', '만장굴', '망상해수욕장', '망양정과 망양해수욕장', '맹씨행단',
       '메타세콰이어 가로수길', '면앙정', '명동성당', '명성황후 생가', '명옥헌 원림', '목면시배유지',
       '목포 근대역사관(1관)', '목포 자연사박물관', '몽촌토성', '무령왕릉', '무릉계곡', '무위사',
       '무이예술관', '무주 구천동계곡 방화동 가족휴양촌,', '무창포해수욕장', '문경새재도립공원', '문무대왕릉',
       '문신미술관', '문장대', '미륵사지', '미황사', '민주공원', '밀양 얼음골', '바람의 언덕',
       '바람흔적미술관', '박경리기념관', '박경리문학공원', '방림원', '방이동 백제 고분군', '방태산 자연휴양림',
       '백남준 아트센터', '백담사', '백련사', '백령도', '백양사', '백운산 자연휴양림', '백제 역사문화관',
       '벌교 홍교, 대한다원', '범어사', '법주사', '법흥사', '벽골제', '별마로천문대', '병산서원', '보경사',
       '보령 석탄박물관', '보림사', '보문사', '보수동 책방골목', '보신각', '복천박물관', '봉은사', '봉정사',
       '봉황동 유적', '부산국제영화제', '부산타워', '부석사', '부소산성', '부안 영상테마파크', '부천 물박물관',
       '부천 활박물관과 궁도장', '부천자연생태박물관과 식물원', '북악산 서울 한양도성', '북촌 돌하르방공원',
       '북촌한옥마을', '분황사', '불갑사', '불국사', '불영사와 불영계곡', '비자림', '빙계계곡', '사직단',
       '산굼부리', '산방굴사', '산방산', '산사원', '산수유마을', '삼년산성', '삼사 해상공원',
       '삼성미술관 리움', '삼성혈', '삼성화재 교통박물관', '삼포 해수욕장', '상당산성', '상수허브랜드',
       '상원사', '상족암군립공원', '상주 자전거박물관', '새별오름', '생각하는 정원', '서대문형무소', '서삼릉',
       '서생포왜성', '서울 약령시장', '서울광장', '서울대공원', '서울숲', '서울역사박물관', '서일농원',
       '서출지', '석굴암', '석봉 도자기미술관', '석빙고', '석장리박물관', '석탄박물관', '선비촌', '선암계곡',
       '선암사', '선운사', '선유도공원', '설악 씨네라마', '설악산 국립공원', '섬진강 기차마을', '섭지코지',
       '성공회 강화읍성당', '성류굴', '성산일출봉', '성읍민속마을', '세리월드', '세미원', '세병관',
       '세종대왕기념관', '세중박물관', '소래포구', '소백산 국립공원', '소설  『토지』 촬영장(최 참판 댁)',
       '소설 『태백산맥』 문학기행', '소쇄원', '소수서원', '소양호', '소인국 테마파크', '속리산 국립공원',
       '속초 등대전망대', '속초시립박물관', '송광사', '송산 공룡알화석지', '송악산', '송정해수욕장',
       '송천 떡마을', '쇠소깍', '수덕사', '수도국산 달동네박물관', '수로왕릉', '수로왕비릉', '수승대',
       '수종사', '수타사', '순천 드라마세트장 ', '순천만 갈대밭', '숭례문', '식영정', '신라역사과학관',
       '신륵사', '신선대', '신성리 갈대밭', '신영 영화박물관', '신지 명사십리해수욕장', '실상사',
       '십리포 해수욕장', '쌍계사', '아부오름', '아인스월드', '아차산북한산국립공원', '아침고요수목원',
       '아프리카박물관', '안면도 자연휴양림', '안면암 부교', '안민도로', '안양 예술공원', '안흥찐빵마을',
       '알뜨르 비행장', '암사동 선사주거지', '애기봉전망대', '애니메이션박물관', '약천사', '양동마을',
       '양떼목장', '양평 들꽃수목원', '어승생오름', '에버랜드', '여미지식물원', '여의도공원', '여좌천',
       '연천 전곡리 유적', '영금정', '영남루', '영녕릉', '영덕 해맞이 공원', '영랑 생가', '영랑호',
       '영평사', '오대산 국립공원', '오동도', '오두산 통일전망대', '오산리 선사유적박물관', '오색 주전골',
       '오설록뮤지엄', '오죽헌', '옥산서원', '옥포대첩기념공원', '온달국민관광지', '온양민속박물관', '올림픽공원',
       '와우정사', '왕곡마을', '왕궁리 오층석탑', '왕인박사 유적지', '외도 해상농원', '외돌개', '외암민속마을',
       '용궁사', '용눈이 오름', '용두산공원', '용두암', '용머리해안', '용문사', '용주사', '용천사',
       '용추계곡', '용흥궁', '우도', '우포늪', '운림산방', '운문사', '운주사', '운현궁', '울릉도',
       '울산 암각화 박물관', '원당 종마목장', '원당 허브랜드', '월드컵공원', '월명공원', '월명암 낙조대',
       '월미도', '월악산 국립공원', '월정사', '월출산 국립공원', '유달산', '유달산조각공원', '유럽자기박물관',
       '율포해수욕장과 해수녹차탕', '융ㆍ건릉', '은해사', '을왕리해수욕장', '음성 큰바위얼굴 조각공원', '이기대',
       '이중섭 미술관', '이화벽화마을', '이효석 문학관과 생가', '익산 보석박물관', '익산 왕궁리 오층석탑',
       '인왕산 선바위와 국사당', '일산 호수공원', '임실치즈테마파크', '임진각 평화누리', '임진성', '자갈치시장',
       '자수정 동굴나라', '자유공원', '장릉', '장복산', '장생포 고래박물관', '장안사', '장전미술관',
       '장흥아트파크', '전등사', '전라남도 해양수산과학관', '전북 도립미술관', '전쟁기념관', '전주 한지박물관',
       '전주한옥마을', '절두산 순교성지와 양화진외국인선교사묘원', '정동진', '정방폭포', '정선5일장',
       '정약용 생가와 묘소', '정지용 문학관과 생가', '제부도', '제오리 공룡 발자국 화석', '제이드가든 수목원',
       '제주 감귤박물관', '제주 관덕정', '제주 민속자연사박물관', '제주 올레', '제주돌문화공원',
       '제주민속촌박물관', '조계사', '조선민화박물관', '종묘', '주남저수지', '주산지', '주실마을',
       '주왕산 국립공원', '주전 몽돌해변', '죽녹원', '죽서루', '죽주산성', '중미산천문대',
       '중앙탑과 충주박물관', '증도 태평염전과 소금박물관', '지리산 국립공원', '지리산 산수유마을', '직지사',
       '진남관', '진도 신비의 바닷길', '진도타워', '진주성', '진해 군항제', '차이나타운',
       '참소리축음기와 에디슨과학박물관', '창경궁', '창녕 석빙고', '창녕박물관', '창덕궁', '창원 해양공원',
       '천곡동굴', '천관산', '천리포수목원', '천은사', '천제연폭포', '천주교 계산 주교좌 성당',
       '천주교 대구대교구 주교좌 계산성당', '천주교 대전교구 공세리성당', '천주교 대전교구 솔뫼성지',
       '천주교 전주교구 전동성당', '천주교 치명자산 성지', '천지연폭포', '철도박물관', '철암역', '첨성대',
       '청간정', '청계천', '청곡사', '청량산과 청량사', '청령포', '청사포', '청송 얼음골',
       '청옥산 육백마지기', '청와대', '청주고인쇄박물관', '청초호', '청평사', '청풍 문화재단지', '추사 고택',
       '추암바위와 추암해변', '춘장대해수욕장', '춘천 인형극장', '춘천마임축제', '충렬사', '충청수영성',
       '치악산 국립공원', '칠장사', '클레이아크 김해미술관', '탄금대', '탑골공원', '태백 석탄박물관',
       '태백산도립공원', '태종대', '태화강 십리대밭', '테디베어뮤지엄', '통도사', '통영 남망산국제조각공원',
       '통영 수산과학관', '통영 옻칠미술관', '통일전망대', '파주 프로방스', '팔공산케이블카', '팜카밀레 허브농원',
       '퍼시픽랜드', '평화박물관', '포석정', '표충사', '풍수원성당', '필례약수', '필룩스조명박물관',
       '하슬라 아트월드', '하조대', '하회마을', '학동 몽돌해수욕장', '한강시민공원', '한국 고건축박물관',
       '한국 대나무박물관', '한국만화박물관', '한국민속촌', '한국은행 화폐금융박물관', '한국이민사박물관',
       '한국자생식물원', '한국천연염색문화관', '한라산 국립공원', '한림공원', '한벽당', '한택식물원',
       '함덕 서우봉 해변', '함안박물관', '함평 나비축제', '합천 영상테마파크', '항공우주박물관',
       '항파두리 항몽유적지', '해강 도자미술관', '해남 공룡박물관', '해녀박물관', '해동용궁사', '해망굴',
       '해미읍성', '해신당공원', '해운대', '해운대 달맞이길', '해인사', '해저터널', '행주산성', '향일암',
       '허브아일랜드', '헌인릉', '헤이리 문화예술마을', '현충사', '협재', '호암미술관', '홍도', '홍릉수목원',
       '화성', '화순 고인돌 군락', '화암동굴과 천포금광촌', '화엄사', '화진포 해양박물관', '화진포해수욕장',
       '화천 산천어축제', '환선굴', '황룡사지', '황매산 군립공원', '황지', '회암사지', '휴애리 자연생활공원',
       '흑산도', '흥정계곡과 허브나라'], dtype=object)

In [127]:
df2['여행지'].unique() - dfs['여행지'].unique()

ValueError: operands could not be broadcast together with shapes (652,) (612,)

In [161]:
for i in range(len(df2)):
    if df2['여행지'][i] in dfs['여행지']:
        print('True')

In [166]:
df2['여행지'][0] in dfs['여행지']

False

In [167]:
df2['여행지']

49                63스퀘어
529             BIFF 광장
538    SEA LIFE 부산아쿠아리움
522            가야산 국립공원
269                 간월재
             ...
170                  황지
108                회암사지
608          휴애리 자연생활공원
396                 흑산도
200          흥정계곡과 허브나라
Name: 여행지, Length: 658, dtype: object

In [168]:
dfs['여행지']

0                 63스퀘어
1               BIFF 광장
2      SEA LIFE 부산아쿠아리움
3              가야산 국립공원
4                   간월재
             ...
613                  황지
614                회암사지
615          휴애리 자연생활공원
616                 흑산도
617          흥정계곡과 허브나라
Name: 여행지, Length: 618, dtype: object